language: python
cache:
  - pip
  - yarn
python:
  - "3.6"

addons:
  apt:
    packages:
      - libssl-dev
      - build-essential
services:
  - postgresql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./manage.py migrate
  - nvm install node && nvm use node && npm i -g yarn
install:
  - pip install -r requirements.txt
  - pip install flake8 pylint pylint_django
  - yarn install
script:
  - flake8 .
  - find . ! -path "./node_modules/*" ! -path "./env/*" ! -path "*/migrations/*" ! -path "*/snapshots/*" -iname "*.py" | xargs pylint --load-plugins pylint_django
  - pytest
  - yarn run test -- --ci
