language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./manage.py migrate
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - flake8 .
  - pytest
