# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 14:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_auto_20171102_1445'),
        ('trading', '0005_auto_20171015_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Quantity can not be negative')])),
            ],
        ),
        migrations.RemoveField(
            model_name='trade',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stock',
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_account', to='authentication.Profile'),
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.AddField(
            model_name='tradestock',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.TradingAccount'),
        ),
        migrations.AddField(
            model_name='tradestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.Stock'),
        ),
        migrations.AddField(
            model_name='tradebucket',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckettrades', to='trading.TradingAccount'),
        ),
        migrations.AddField(
            model_name='tradebucket',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckettrades', to='stocks.InvestmentBucket'),
        ),
    ]
