# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20171030_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebucket',
            name='quantity',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0, message='Quantity can not be negative')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradestock',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Quantity can not be negative')]),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_account', to='authentication.Profile'),
        ),
    ]
