# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20171102_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebucket',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
