# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20171102_0240'),
        ('trading', '0006_auto_20171030_2116'),
    ]

    operations = [
    ]
