# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('authentication', '0001_initial'), ('authentication', '0002_profile_has_bank_linked'), ('authentication', '0003_userbank'), ('authentication', '0004_userbank_institution_name'), ('authentication', '0005_auto_20171011_1314'), ('authentication', '0006_auto_20171109_1333'), ('authentication', '0007_remove_profile_has_bank_linked')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbank', to=settings.AUTH_USER_MODEL)),
                ('institution_name', models.CharField(default='tb', max_length=1000)),
                ('account_name_field', models.CharField(default='Dummy account name', max_length=1000)),
                ('current_balance_field', models.FloatField(default=0.0)),
                ('expenditure_field', models.FloatField(default=0.0)),
                ('income_field', models.FloatField(default=0.0)),
            ],
        ),
    ]
