# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 15:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stocks.stock_helper


class Migration(migrations.Migration):

    replaces = [('stocks', '0001_initial'), ('stocks', '0002_auto_20170920_0123'), ('stocks', '0003_investmentbucket_investmentstockconfiguration'), ('stocks', '0004_auto_20171011_1324'), ('stocks', '0005_auto_20171011_1408'), ('stocks', '0006_auto_20171011_1412'), ('stocks', '0007_auto_20171011_1415'), ('stocks', '0008_investmentbucketdescription_is_good'), ('stocks', '0009_auto_20171011_1910'), ('stocks', '0010_investmentbucket_total'), ('stocks', '0011_auto_20171013_0113'), ('stocks', '0012_auto_20171013_0118'), ('stocks', '0013_auto_20171013_0307'), ('stocks', '0014_auto_20171014_1355'), ('stocks', '0015_auto_20171014_1627'), ('stocks', '0016_auto_20171015_1524'), ('stocks', '0017_auto_20171015_1528'), ('stocks', '0018_auto_20171015_1529'), ('stocks', '0019_auto_20171030_2116'), ('stocks', '0020_auto_20171102_1226')]

    initial = True

    dependencies = [
        ('authentication', '0005_auto_20171011_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailystockquote',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quote', to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='dailystockquote',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailystockquote',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Daily stock quote can not be negative')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailystockquote',
            unique_together=set([('stock', 'date')]),
        ),
        migrations.CreateModel(
            name='InvestmentBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentStockConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='The quantity can not be negative.')])),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.InvestmentBucket')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='stocks.Stock')),
                ('end', models.DateField(blank=True, null=True)),
                ('start', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentBucketDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message='The description should at least be 3 characters long.')])),
                ('bucket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='stocks.InvestmentBucket')),
                ('is_good', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='investmentbucket',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bucket', to='authentication.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentbucket',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentbucket',
            name='available',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='The available money can not be negative.')]),
        ),
        migrations.AlterField(
            model_name='investmentbucket',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='The name should not be empty.')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='The name should not be empty.')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='The ticker should not be empty.')]),
        ),
        migrations.AlterUniqueTogether(
            name='investmentbucket',
            unique_together=set([('name', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='investmentbucketdescription',
            unique_together=set([('text', 'bucket')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='The ticker should not be empty.'), stocks.stock_helper.validate_ticker]),
        ),
    ]
